ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true  # 2D 환경이라면 true
    publish_acceleration: false
    publish_tf: true  # odom -> base_link 발행
    
    # 프레임 설정
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    
    # Wheel Odometry
    odom0: /wheel/odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false
    odom0_queue_size: 10

    # IMU (with covariance)
    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  true,  true,  true]
    imu0_differential: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true


