controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Joint State Broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Ackermann Steering Controller
    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

# Ackermann Steering Controller Configuration
ackermann_steering_controller:
  ros__parameters:
    # Rear wheels (traction/drive)
    rear_wheels_names:
      - left_rear_wheel_joint
      - right_rear_wheel_joint

    # Front wheels (passive)
    front_wheels_names:
      - left_front_wheel_joint
      - right_front_wheel_joint

    # Steering joints
    left_steering_joint_name: left_steering_hinge_joint
    right_steering_joint_name: right_steering_hinge_joint

    # Vehicle geometry (from F1TENTH specs)
    wheelbase: 0.3302  # meters
    front_wheel_track: 0.2413  # meters (wheel_separation)
    rear_wheel_track: 0.2413   # meters
    wheel_radius: 0.0508  # meters

    # Steering limits
    front_steering_angle_limit: 0.4189  # radians (±24 degrees)
    rear_steering_angle_limit: 0.0  # rear wheels don't steer

    # Command timeout
    cmd_vel_timeout: 0.5  # seconds

    # Topic configuration
    reference_timeout: 0.5
    use_stamped_vel: false

    # Odometry
    enable_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    # Open loop (no velocity feedback)
    open_loop: false

    # Position feedback from steering joints
    position_feedback: true

# Joint State Broadcaster Configuration
joint_state_broadcaster:
  ros__parameters:
    extra_joints: []
