controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Velocity Controllers for wheels
    left_rear_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_rear_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    left_front_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_front_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    # Position Controllers for steering
    left_steering_controller:
      type: position_controllers/JointGroupPositionController

    right_steering_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Wheel velocity controllers
left_rear_wheel_velocity_controller:
  ros__parameters:
    joints:
      - left_rear_wheel_joint

right_rear_wheel_velocity_controller:
  ros__parameters:
    joints:
      - right_rear_wheel_joint

left_front_wheel_velocity_controller:
  ros__parameters:
    joints:
      - left_front_wheel_joint

right_front_wheel_velocity_controller:
  ros__parameters:
    joints:
      - right_front_wheel_joint

# Steering position controllers
left_steering_controller:
  ros__parameters:
    joints:
      - left_steering_hinge_joint

right_steering_controller:
  ros__parameters:
    joints:
      - right_steering_hinge_joint

# Joint state broadcaster
joint_state_broadcaster:
  ros__parameters:
    joints:
      - left_rear_wheel_joint
      - right_rear_wheel_joint
      - left_front_wheel_joint
      - right_front_wheel_joint
      - left_steering_hinge_joint
      - right_steering_hinge_joint
